language: node_js

cache:
  directories:
    - "node_modules"

script:
  - npm run build
  - npm test -- -u --coverage

after_success: bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
